# Generated by Django 3.0 on 2021-03-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=194, verbose_name='Descrição')),
                ('anonimo', models.BooleanField(verbose_name='Anônimo')),
                ('voto_unico', models.BooleanField(verbose_name='Voto Único')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_termino', models.DateField(verbose_name='Data Término')),
            ],
            options={
                'verbose_name': 'Votaçao',
                'db_table': 'votacao',
            },
        ),
        migrations.CreateModel(
            name='OpcaoVoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('numero_votos', models.IntegerField(verbose_name='Número Votos')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Votacao')),
            ],
            options={
                'verbose_name': 'Opção de voto',
                'verbose_name_plural': 'Opções de voto',
                'db_table': 'opcaovoto',
            },
        ),
    ]
