# Generated by Django 3.0 on 2021-03-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votacao',
            options={'verbose_name': 'Votação', 'verbose_name_plural': 'Votações'},
        ),
    ]
