# Generated by Django 3.0 on 2021-03-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210324_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='numero_votos',
            field=models.IntegerField(default=0, verbose_name='Número Votos'),
        ),
    ]
