# Generated by Django 3.0 on 2021-03-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoavoto',
            options={'verbose_name': 'Voto da Pessoa', 'verbose_name_plural': 'Voto das Pessoas'},
        ),
        migrations.AlterModelTable(
            name='pessoavoto',
            table='pessoavoto',
        ),
    ]
