# Generated by Django 3.0 on 2021-03-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210324_1757'),
        ('adm', '0002_auto_20210324_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoavoto',
            name='opcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.OpcaoVoto', verbose_name='Opção de voto'),
        ),
        migrations.AlterField(
            model_name='pessoavoto',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Pessoa', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoavoto',
            name='votacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Votacao', verbose_name='Votação'),
        ),
    ]
