# Generated by Django 3.0 on 2021-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20210324_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoavoto',
            name='numero_votos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de votos'),
        ),
    ]
